# information needed when viewing a single project
campaign = {'title': 'The Campaign',
			'author': 'John Doe',
			'description': '100 character description or something of that sorts',
			'currentPrice': 53.23,
			'nextPrices': [50.00,45.00,42.00],
			'pledgesNeeded' : [100, 150, 200, 250],
			'mainImage': 'some image',
			'percentFunded': 50,
			};

# data relating all projects in the database
allprojects = [
		{
			'image':'theUrl', 
			'title':'campaignTitle1', 
			'author': 'Saqib Banna',
			'shortDescription':'Nam sit amet est sapien, a faucibus purus. Sed commodo facilisis tempus. Pellentesque placerat elementum adipiscing.',
			'currentPrice':80,
			'amountCommitted':20,
			'daysLeft':10,
			'nextPrice':70,
			'nextCommitAmount':30,
			'percentCommitted':40,
		},
		{
			'image':'theUrl', 
			'title':'campaignTitle2', 
			'author': 'Robert',
			'shortDescription':'Nam sit amet est sapien, a faucibus purus. Sed commodo facilisis tempus. Pellentesque placerat elementum adipiscing.',
			'currentPrice':80,
			'amountCommitted':20,
			'daysLeft':10,
			'nextPrice':40,
			'nextCommitAmount':50,
			'percentCommitted':70,
		},
		{
			'image':'theUrl', 
			'title':'campaignTitle3', 
			'author': 'Brandon',
			'shortDescription':'Nam sit amet est sapien, a faucibus purus. Sed commodo facilisis tempus. Pellentesque placerat elementum adipiscing.',
			'currentPrice':80,
			'amountCommitted':20,
			'daysLeft':10,
			'nextPrice':20,
			'nextCommitAmount':100,
			'percentCommitted':20,
		},
		{
			'image':'theUrl', 
			'title':'campaignTitle4', 
			'author': 'Alexa',
			'shortDescription':'Nam sit amet est sapien, a faucibus purus. Sed commodo facilisis tempus. Pellentesque placerat elementum adipiscing.',
			'currentPrice':60,
			'amountCommitted':20,
			'daysLeft':10,
			'nextPrice':30,
			'nextCommitAmount':40,
			'percentCommitted':99,
		},
	]